name:                kellisp
version:             0.1.0.0
github:              "zackbach/kellisp"
license:             BSD3
author:              "Zack Eisbach"
maintainer:          "zack.eisbach@gmail.com"
copyright:           "2023 Zack Eisbach"

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            A simple Lisp implementation in Haskell
category:            Compilers/Interpreters

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/zackbach/kellisp#readme>

dependencies:
- base >= 4.7 && < 5
- haskeline
- text
- containers
- megaparsec
- mtl
- case-insensitive

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  kellisp-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kellisp

tests:
  kellisp-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kellisp
    - hspec
    - hspec-megaparsec
    build-tools:
    - hspec-discover
